server:
  port: 18083

spring:
  application:
    name: dubbo-consumer

  ##  dubbo springboot 配置
  dubbo:
    application:
      id: dubbo-consumer
      name: dubbo-consumer
    registry:
      address: zookeeper://127.0.0.1:2181

    #      protocol: zookeeper
#      address: 127.0.0.1
#      port: 2181
#      subscribe: true
    protocol:
      name: dubbo
#      host: 127.0.0.1
      port: 20880
    provider:
      filter: tracing
    consumer:
      filter: tracing
  sleuth:
    propagation-keys:
      - x-request-id
      - x-fix-request-id
    trace-id128: true
